[package]
name = "tor-async-utils"
version = "0.36.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Async/futures helpers for use with Tor"
keywords = ["tor", "arti"]
# We must put *something* here and this will do
categories = ["rust-patterns"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
cfg-if = "1.0.0"
derive-deftly = { version = "~1.5.0", features = ["full", "beta"] }
educe = "0.4.22"
futures = "0.3.14"
oneshot-fused-workaround = { path = "../oneshot-fused-workaround", version = "0.5.0" }
pin-project = "1"
postage = { version = "0.5.0", default-features = false, features = ["futures-traits"] }
rand = "0.9.1"
slotmap-careful = { path = "../slotmap-careful", version = "0.5.0" }
sync_wrapper = "1.0.2"
thiserror = "2"
tokio = { version = "1.7", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "time"], optional = true }
tokio-util = { version = "0.7.0", features = ["compat"], optional = true }
tor-rtcompat = { version = "0.36.0", path = "../tor-rtcompat" }
tracing = "0.1.36"
visibility = { version = "0.1.0" }
void = "1"

[dev-dependencies]
futures-await-test = "0.3.0"
tokio = { version = "1.7", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "time"] }
tokio-util = { version = "0.7.0", features = ["compat"] }
tor-error = { path = "../tor-error", version = "0.36.0" }
tor-rtmock = { path = "../tor-rtmock", version = "0.36.0" }

[features]
full = [
    "oneshot-fused-workaround/full",
    "slotmap-careful/full",
    "tokio",
    "tokio-util",
    "tor-rtcompat/full",
]
