//! Derive-deftly macro for deriving configuration objects.
//!
//! The macro defined here makes a configuration object
//! able to participate in the arti configuration system by giving
//! it a Builder type implementing the appropriate serde traits.
//!
//! It is more ergonomic and less error-prone for our purposes than
//! `derive_builder`.
//!
//! ## Basic usage:
//!
//! ```
//! use derive_deftly::Deftly;
//! use tor_config::derive::prelude::*;
//!
//! #[derive(Deftly, Clone, Debug, PartialEq)]
//! #[derive_deftly(TorConfig)]
//! pub struct ExampleConfig {
//!     #[deftly(TorConfig(default))]
//!     owner_uid: Option<u32>,
//!
//!     #[deftly(TorConfig(default = r#" "~".to_string() "#))]
//!     path: String,
//! }
//! ```
//! For topic-specific information, see one of the following:
//!
//! * [How to declare a configuration type](doc_howto)
//! * [Code generated by the TorConfig macro](doc_generated_code)
//! * [Migrating from derive_builder](doc_migration)
//! * [Reference: Attributes supported by the TorConfig macro](doc_ref_attrs)
//! * [Differences from derive_builder](doc_differences)
//! * [Types with special handling](doc_special_types)

/// How to declare a configuration type
///
/// ## Getting started
///
/// Every configuration type should implement at least `Clone` and `Debug`;
/// it should almost[^partialeq-notest] always implement `PartialEq` too.
/// In addition to these, you should use `derive(Deftly)` and `derive_deftly(TorConfig)`
/// to use this macro.
///
/// You can start out by copying this template:
///
/// ```
/// use derive_deftly::Deftly;
/// use tor_config::derive::prelude::*;
///
/// #[derive(Deftly, Clone, Debug, PartialEq)]
/// #[derive_deftly(TorConfig)]
/// pub struct XyzzyConfig {
///     // ...
/// }
/// ```
///
/// ## Declaring fields
///
/// At this point, you start declaring the fields that should appear in the configuration.
/// You declare them as struct fields (as usual);
/// but to avoid mistakes, you need to specify the default behavior for each field.
/// You typically do this in one of the following ways:
///
/// ```
/// # use derive_deftly::Deftly;
/// # use tor_config::derive::prelude::*;
/// # fn some_function() -> u32 { 7 }
/// # #[derive(Deftly, Clone, Debug, PartialEq)]
/// # #[derive_deftly(TorConfig)]
/// # pub struct Foo {
///
/// // If the user doesn't set this field, we set it by calling some_function().
/// #[deftly(TorConfig(default="some_function()"))]
/// value1: u32,
///
/// // If the user doesn't set this field, we set it by calling Default::default().
/// #[deftly(TorConfig(default))]
/// value2: String,
///
/// // This field has no default!  It's an error if the user doesn't set this.
/// // (See warnings on no_default below.)
/// #[deftly(TorConfig(no_default))]
/// value3: u16,
/// # }
/// ```
///
/// Notes:
/// - There is no "default" behavior for the unset fields: you need to say which one you want.
///   This requirement is meant to avoid programming errors.
/// - Try to avoid using `no_default` on any configuration element unless you truly want the user
///   to specify it in their configuration file every time this section exists.
///   It's okay to use `no_default`
///   on something like the address of a fallback directory
///   (where each one needs to be fully specified)
///   or the nickname of an onion service
///   (which needs to be specified for every onion service that exists).
/// - If you use `no_default`, you will need to use [`no_impl_default`] on the structure
///   as a whole.
///
/// ## Other things you can do
///
/// There are many other attributes you can set on struct and fields
/// to control their behavior.
/// See [the reference](doc_ref_attrs) for more information.
///
/// <!-- TODO: Write a cookbook for common patterns. -->
///
/// [^partialeq-notest]: If you decide not to implement `PartialEq` for some reason,
///    you will need to use the [`no_test_default`] attribute to suppress a test that requires it.
///    (I do not really know why you would do this.  Just implement `PartialEq`, or
///    edit this documentation to explain why people would sometimes not want to implement it.)
///
/// [`no_impl_default`]: crate::derive::doc_ref_attrs#tmeta:no_impl_default
/// [`no_test_default`]: crate::derive::doc_ref_attrs#tmeta:no_test_default
pub mod doc_howto {}

/// Code generated by the TorConfig macro
///
/// > Here we describe the code generated by the `derive_deftly(TorConfig)` macro.
/// > Note that this is the _default_ behavior;
/// > particular [attributes](doc_ref_attrs) not described here will override it.
///
/// <!-- TODO: Add "See: X" notes links to the options that override each thing? -->
///
/// The `TorConfig` macro generates a Builder struct, with a name formed by appending
/// `Builder` to the name of the configuration struct.
/// That is, if the configuration struct is `MyConfig`,
/// the macro generates `MyConfigBuilder`.
///
/// The builder struct has the same visibility as the configuration struct.
/// The builder struct has,
/// for every ordinary field[^ordinary] of type T in the configuration struct,
/// a field with the same name and type `Option<T>`.
/// For every [sub-builder] field in the configuration struct of type `T`,
/// it has a field with the same name and the type `TBuilder`.
/// These fields are private.
///
/// The builder struct implements [`serde::Serialize`] and [`serde::Deserialize`].
/// Every field is marked with `#[serde(default)]` to allow it to be absent
/// in the toml configuration.
///
/// The builder struct derives `Default`, `Clone`, and `Debug`.
/// It also has a `new()` method that calls `Default::default()`
///
/// The _configuration struct_ receives a generated "builder" method,
/// of type `fn () -> MyConfigBuilder`.
/// This function calls the builder's `Default::default()` method.
///
/// For every ordinary[^ordinary] field of type T in the configuration struct,
/// the builder has a **setter method** with the same name,
/// of type `fn (&mut self, value: T) -> &mut Self`.
/// The setter method sets the corresponding field in `self` to `Some(value)`,
/// and returns `self``.
///
/// For every [sub-builder] field of type SubCfg in the configuration struct,
/// the builder has an accessor method with the same name,
/// returning `&mut SubCfgBuilder`.
///
/// The builder has a **build method**, with the name `build`,
/// of type `fn (&self) -> Result<MyConfig, ConfigBuildError>`.
/// It has the same visibility as the builder struct.
/// For every field in the builder of value `Some(x)`,
/// it sets the corresponding field in the configuration object to `x`.
/// For every field in the builder of value `None`,
/// it sets the corresponding field in the configuration object to its default,
/// or returns an error,
/// depending on the attributes set on the field.
/// For every field in the builder with a [sub-builder],
/// it invokes the build method on that sub-builder,
/// and sets the corresponding field in the configuration object to its result.
///
/// A new `#[cfg(test)]` module is generated, with tests for the builder behavior.
/// This module is called `test_my_config_builder`, with `my_config` replaced with the
/// snake-case name of your actual configuration type.
///
/// [^ordinary]: For the purpose of this documentation,
///     a field is "ordinary" if it does not have a [sub-builder].
///
///
/// [sub-builder]: crate::derive::doc_ref_attrs#fmeta:sub_builder
pub mod doc_generated_code {}

/// Migrating from derive_builder.
///
/// TODO: Write this?  Or just migrate?
///
pub mod doc_migration {}

/// Reference: Attributes supported by the TorConfig macro
///
/// * [Top-level attributes](crate::derive::doc_ref_attrs#tmeta)
/// * [Field-level attributes](crate::derive::doc_ref_attrs#fmeta)
///
/// <div id="tmeta">
///
/// ## Top-level attributes
///
/// </div>
///
/// These attributes can be provided at the top-level, right after
/// `derive_deftly(TorConfig)` and before `pub struct FooConfig`.
///
/// <div id="tmeta:no_impl_serialize">
///
/// ### `deftly(TorConfig(no_impl_serialize))`  — Don't derive Serialize for the builder struct
///
/// </div>
///
/// By default, the generated Builder will derive [`serde::Serialize`].
/// This attribute suppresses that behavior.
///
///
/// <div id="tmeta:no_impl_deserialize">
///
/// ### `deftly(TorConfig(no_impl_deserialize))` — Don't derive Deserialize for the builder struct
///
/// </div>
///
/// By default, the generated Builder will implement [`serde::Deserialize`].
/// This attribute suppresses that behavior.
///
/// Using this option will prevent your type from participating directly
/// in the Arti configuration system.
///
/// <div id="tmeta:no_impl_default">
///
/// ### `deftly(TorConfig(no_impl_default))` — Don't derive Default for the config struct
///
/// </div>
///
/// By default, the macro will derive [`Default`] on the configuration type
/// by creating a default builder, and constructing the configuration type with it.
///
/// <div id="tmeta:no_test_default">
///
/// ### `deftly(TorConfig(no_test_default))` — Don't test Default for the config struct
///
/// </div>
///
/// By default, the macro will implement a test to make sure that its generated `Default`
/// implementation produces the same result as deserializing an empty configuration builder,
/// and building it.
/// This attribute prevents that test from being generated.
///
/// The test is also omitted when [`no_impl_default`] or [`no_impl_deserialize`] is given.
///
/// > Note: You must specify this option if the configuration type has any generic parameters.
/// > Otherwise, it's best to avoid this attribute.
/// >
/// > TODO: We should remove this limitation if we can.
///
/// <div id="tmeta:no_impl_builder_trait">
///
/// ### `deftly(TorConfig(no_impl_builder_trait))` — Don't derive Builder for the builder struct
///
/// </div>
///
/// By default, the builder will implement [`tor_config::load::Builder`](crate::load::Builder).
/// This attribute suppresses that behavior.
///
/// > This attribute's name ends with `_trait` to remind the caller that the Builder struct itself
/// > will still be implemented.
///
/// <div id="tmeta:attr">
///
/// ### `deftly(TorConfig(attr = ".."))` — Apply an attribute to the builder struct
///
/// </div>
///
/// This attribute passes its contents through to a new attribute on the derived builder struct.
/// For example, you can make the builder derive `PartialOrd` by saying
///
/// ```no_compile
/// #[deftly(TorConfig(attr= "derive(PartialOrd)"))]
/// ```
///
/// (See also [`attr`](crate::derive::doc_ref_attrs#fmeta:attr) for fields.)
///
/// <div id="tmeta:validate">
///
/// ### `deftly(TorConfig(validate = ".."))` — Call a function before building
///
/// </div>
///
/// This attribute makes the generated `build()` method call a validation function on itself
/// **before** it builds the configuration.  The function must take `&FooBuilder`
/// as an argument, and return `Result<(),ConfigBuildError>`.  If the function
/// returns an error, then the build method fails with that error.
///
/// Example:
/// ```
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// #[deftly(TorConfig(validate="Self::must_be_odd"))]
/// pub struct FavoriteOddNumber {
///     #[deftly(TorConfig(default="23"))]
///     my_favorite: u32,
/// }
///
/// impl FavoriteOddNumberBuilder {
///     fn must_be_odd(&self) -> Result<(), ConfigBuildError> {
///         let Some(fav) = self.my_favorite else { return Ok(()); };
///         if fav % 2 != 1 {
///             return Err(ConfigBuildError::Invalid {
///                 field: "my_favorite".to_string(),
///                 problem: format!("{fav} was not an odd number")
///             })
///         }
///         Ok(())
///     }
/// }
/// ```
///
/// <!-- TODO: Add a "see also" note. -->
///
/// <div id="tmeta:post_build">
///
/// ### `deftly(TorConfig(post_build = ".."))` — Call a function after building
///
/// </div>
///
/// This attribute makes the generated `build()` method call a validation function
/// on the configuration **after** it is built.
/// The function must take the the configuration
/// _by value_ as an argument,
/// and `Result<`(the configuration)`,ConfigBuildError>`.  If the function
/// returns an error, then the build method fails with that error.
///
/// Example:
/// ```
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// #[deftly(TorConfig(post_build="FavoriteEvenNumber::must_be_even"))]
/// pub struct FavoriteEvenNumber {
///     #[deftly(TorConfig(default="86"))]
///     my_favorite: u32,
/// }
///
/// impl FavoriteEvenNumber {
///     fn must_be_even(self) -> Result<Self, ConfigBuildError> {
///         if self.my_favorite % 2 != 0 {
///             return Err(ConfigBuildError::Invalid {
///                 field: "my_favorite".to_string(),
///                 problem: format!("{} was not an even number", self.my_favorite)
///             })
///         }
///         Ok(self)
///     }
/// }
/// ```
///
/// > Note:
/// > You can also use this attribute to clean up or normalize the the configuration object.
///
/// <div id="tmeta:vis">
///
/// ### `deftly(TorConfig(vis = ".."))` — Change visibility of the builder
///
/// </div>
///
/// By default, the builder struct is generated with the same visibility as the
/// configuration struct.
/// You can use this attribute to change its visibility.
///
///
/// <div id="tmeta:build_fn_name">
///
/// ### `deftly(TorConfig(build_fn(name = "..")))` — Change name of the build method
///
/// </div>
///
/// By default, the generated build method is called `build`.
/// You can use this attribute to change its name.
///
/// <div id="tmeta:vis">
///
/// ### `deftly(TorConfig(build_fn(vis = "..")))` — Change visibility of the build method
///
/// </div>
///
/// By default, the `build()` method has the same visibility as the builder struct.
/// You can use this attribute to change its visibility.
///
/// See also:
/// * [`deftly(TorConfig(vis = ".."))`](crate::derive::doc_ref_attrs#tmeta:vis)
///
/// <div id="fmeta">
///
/// ## Field-level attributes
///
/// </div>
///
/// <div id="fmeta:default_default">
///
/// ### `deftly(TorConfig(default)))` — Use Default::default() when no value is provided
///
/// </div>
///
/// When this attribute is provided, if the given field is absent in the builder,
/// the `build()` method will set its value to `Default::default()`.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
/// <div id="fmeta:default_equals">
///
/// ### `deftly(TorConfig(default = "..")))` — Use a given value when no value is provided
///
/// </div>
///
/// When this attribute is provided, if the given field is absent in the builder,
/// the `build()` method will set its value to the value of the provided expression.
/// The expression may invoke a function, but cannot use `self`.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
///
/// <div id="fmeta:no_default">
///
/// ### `deftly(TorConfig(no_default))` — Do not provide a default for this field.
///
/// </div>
///
/// When this attribute is provided, if the given field is absent in the builder,
/// the `build()` method will fail with an error.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
/// > When you set this attribute on a field, you must also set the top-level
/// > [`no_impl_default`] attribute,
/// > since there will not be a meaningful value for the configuration struct.
/// >
/// > Don't use this option on any config struct that's always present with a multiplicity of one,
/// > or else the empty configuration will become invalid.
///
/// <div id="fmeta:build">
///
/// ### `deftly(TorConfig(build = ".."))` — Call a function to build this field.
///
/// </div>
///
/// When this attribute is provided, you can completely override the way that this field is constructed.
/// The expression must evaluate to a function taking `&Builder` as an argument,
/// and returning the type of the field.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
/// > Be careful with this attribute: it can lead to counterintuitive behavior for the end user.
///
/// Example:
///
/// ```
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// pub struct LowercaseExample {
///     #[deftly(TorConfig(build="Self::build_lc"))]
///     lc: String,
/// }
/// impl LowercaseExampleBuilder {
///     fn build_lc(&self) -> String {
///         let s = self.lc.as_ref().map(String::as_str).unwrap_or("");
///         s.to_lowercase()
///     }
/// }
/// ```
///
/// <div id="fmeta:try_build">
///
/// ### `deftly(TorConfig(try_build = ".."))` — Call a fallible function to build this field.
///
/// </div>
///
/// When this attribute is provided, you can completely override the way that this field is constructed.
/// The expression must evaluate to a function taking `&Builder` as an argument,
/// and returning `Result<T, ConfigBuildError>`, where `T` is the type of the field.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
/// > Be careful with this attribute: it can lead to counterintuitive behavior for the end user.
///
/// Example:
///
/// ```
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// pub struct SqrtExample {
///     #[deftly(TorConfig(try_build="Self::build_sqrt"))]
///     val: f64,
/// }
/// impl SqrtExampleBuilder {
///     fn build_sqrt(&self) -> Result<f64, ConfigBuildError> {
///         let v = self.val.unwrap_or(0.0).sqrt();
///         if v.is_nan() {
///             return Err(ConfigBuildError::Invalid {
///                 field: "val".to_string(),
///                 problem: format!("{v} was negative")
///             })
///         }
///         Ok(v)
///     }
/// }
/// ```
///
/// <div id="fmeta:sub_builder">
///
/// ### `deftly(TorConfig(sub_builder))` — Declare a field to contain a nested configuration
///
/// </div>
///
/// This attribute is what allows configuration structures to nest.
/// When you set this attribute on a field of type `InnerCfg`,
/// the builder structure will contain a field of type `InnerCfgBuilder`.
/// In order to construct the field, the `build()` method will call
/// `InnerCfgBuilder::build()`.
///
/// For each field, you must specify exactly one of
/// [`default`], [`default =`], [`no_default`], [`build`], [`try_build`], or [`sub_builder`].
///
/// <div id="fmeta:sub_builder_build_fn">
///
/// ### `deftly(TorConfig(sub_builder(build_fn = "...")))` — Call a different function on this sub-builder
///
/// </div>
///
/// By default, when [`sub_builder`] is in use,
/// the `build()` method is used to generate the inner configuration object.
/// This attribute changes the name of the function that is called on the inner builder.
///
/// <div id="fmeta:setter_name">
///
/// ### `deftly(TorConfig(setter(name = "..")))` — Change the name of the setter function
///
/// </div>
///
/// By default, the setter function for a field has the same name as its field.
/// You can provide a different name in this attribute.
///
/// <div id="fmeta:setter_vis">
///
/// ### `deftly(TorConfig(setter(vis = "..")))` — Change the visibility of the setter function
///
/// </div>
///
/// By default, the setter function for a field has the same visibility as the builder type.
/// You can provide a different visibility in this attribute.
///
/// <div id="fmeta:setter_skip">
///
/// ### `deftly(TorConfig(setter(skip)))` — Do not generate a setter function
///
/// </div>
///
/// By default, the builder generates a setter function for every field.
/// You can tell it not to do so for a single field by providing this attribute.
///
///
/// <div id="fmeta:setter_into">
///
/// ### `deftly(TorConfig(setter(into)))` — Have the setter function accept `impl Into<T>`
///
/// </div>
///
/// By default, the setter function expects an argument of type `T`,
/// where `T` is the same type of the field.
/// When this option is provided, the setter instead expects an argument of type `impl Into<T>`,
/// and calls [`Into::into`] on it to set the field.
///
/// <div id="fmeta:setter_try_into">
///
/// ### `deftly(TorConfig(setter(try_into)))` — Have the setter function accept `impl TryInto<T>`
///
/// </div>
///
/// By default, the setter function expects an argument of type `T`,
/// where `T` is the same type of the field.
/// When this option is provided, the setter instead expects an argument of type `impl TryInto<T>`,
/// and calls [`TryInto::try_into`] on it to set the field.
/// If `try_into` returns an error, the setter function returns that error.
///
/// <div id="fmeta:setter_strip_option">
///
/// ### `deftly(TorConfig(setter(strip_option)))` — Have the setter for `Option<T>` accept `T`
///
/// </div>
///
/// This attribute requires that the field itself have type `Option<T>` for some T.
/// Instead of taking `Option<T>` as an argument, the setter now accepts a trait that can be either
/// `Option<T>` _or_ `T`.
///
///
/// <div id="fmeta:field_ty">
///
/// ### `deftly(TorConfig(field(ty = "..")))` — Change the type of a field in the builder
///
/// </div>
///
/// By default, for every field of type `T` in the configuration,
/// the builder has a field of type `Option<T>`.
/// This attribute changes the type of the field in the builder to the provided type.
///
/// > This attribute has no effect on the generated setter or builder code.
/// > Therefore, you will typically need to use it along with
/// > the [`setter(skip)`] and [`build`] field attributes.
///
/// Example:
///
/// ```
/// # #![allow(unexpected_cfgs)]
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[derive(Clone,Debug,PartialEq)]
/// pub struct ParsedValue {
///    // ...
/// }
/// impl std::str::FromStr for ParsedValue {
///     type Err = String;
///     fn from_str(s: &str) -> Result<Self, Self::Err> {
///         // ...
/// #       unimplemented!()
///     }
/// }
///
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// pub struct MyConfig {
///     #[deftly(TorConfig(
///         try_build = r#"Self::try_build_behavior"#,
///         field(ty = "Option<String>"),
///         setter(skip)
///     ))]
///     behavior: ParsedValue,
/// }
///
/// impl MyConfigBuilder {
///     pub fn behavior(&mut self, s: impl AsRef<str>) -> &mut Self {
///         self.behavior = Some(s.as_ref().to_string());
///         self
///     }
///     fn try_build_behavior(&self) -> Result<ParsedValue, ConfigBuildError> {
///         self.behavior
///             .as_ref()
///             .map(String::as_str)
///             .unwrap_or("Leave the macro processor. Take the cannoli.")
///             .parse()
///             .map_err(|problem| ConfigBuildError::Invalid {
///                 field: "behavior".to_string(),
///                 problem,
///             })
///     }
/// }
/// ```
///
/// <div id="fmeta:field_vis">
///
/// ### `deftly(TorConfig(field(vis = "..")))` — Change the visibility of a field in the builder
///
/// </div>
///
/// By default, fields in the builder are private.
/// This attribute changes their visibility to the one provided.
///
/// <div id="fmeta:attr">
///
/// ### `deftly(TorConfig(attr = "..")))` — Apply an attribute to the field in the builder
///
/// </div>
///
/// Any attribute provided here is applied to the declared field in the builder.
///
/// Example:
/// ```no_compile
/// #[deftly(TorConfig(attr = "allow(deprecated)"))]
/// x: SomeDeprecatedType,
/// ```
///
/// See also the [`cfg`](crate::derive::doc_ref_attrs#fmeta:cfg) and [`serde`] attributes.
///
/// <div id="fmeta:serde">
///
/// ### `deftly(TorConfig(serde = "..")))` — Apply a serde attribute to the field in the builder
///
/// </div>
///
/// Any serde attribute provided here is applied to the declared field in the builder.
///
/// Example:
/// ```no_compile
/// #[deftly(TorConfig(serde = r#"alias = "old_name_of_field" "#))]
/// current_name_of_field: String,
/// ```
///
/// Attributes applied with `serde` apply after any specified with
/// [`attr`](crate::derive::doc_ref_attrs#fmeta:attr) instead.
///
/// > This is a convenience attribute; you could just use
/// > [`attr`](crate::derive::doc_ref_attrs#fmeta:attr) instead.
///
/// <!-- TODO: write up a list of recommended serde attributes -->
///
/// <div id="fmeta:cfg">
///
/// ### `deftly(TorConfig(cfg = "..")))` — Mark a field as conditionally present
///
/// </div>
///
/// This option causes a field in the builder to be conditionally present or absent at compile time,
/// similar to the ordinary [`cfg`] attribute.
/// However, unlike with the ordinary `cfg` attribute,
/// if the user provides any configuration values for this field when it is disabled,
/// the generated `build()` code will emit a warning via [`tracing`] at runtime telling them
/// what feature they would need to turn on.
///
/// > Note that you _cannot_ use this along with a regular [`cfg`] attribute,
/// > since a regular [`cfg`] attribute would suppress the field altogether.
/// > Therefore, the field will still be present in the configuration struct
/// > even when the `cfg` condition is false.
/// > To work around this limitation, it's conventional to arrange for the type of the field
/// > to be `()` when the `cfg` condition is false.
///
/// Example:
/// ```
/// # #![allow(unexpected_cfgs)]
/// # use derive_deftly::Deftly;
/// # use tor_config::{derive::prelude::*, ConfigBuildError};
/// #[cfg(feature = "rpc")]
/// pub type RpcOptionType = String;
///
/// #[cfg(not(feature = "rpc"))]
/// type RpcOptionType = ();
///
/// #[derive(Clone,Debug,PartialEq,Deftly)]
/// #[derive_deftly(TorConfig)]
/// pub struct OnionSoupConfig {
///     #[deftly(TorConfig(cfg = r#" feature="rpc" "#))]
///     #[deftly(TorConfig(default))]
///     rpc_option: RpcOptionType,
/// }
/// ```
///
/// <!-- TODO: This is a warning now, since it is in general only a warning
///      to use an option that is not recognized.
///      We may want to provide a variant that produces an error instead. -->
///
/// <div id="fmeta:no_magic">
///
/// ### `deftly(TorConfig(no_magic)))` — Disable special handling based on a field's type
///
/// </div>
///
/// **This attribute is likely to be removed and replaced with something
/// marginally less magical.**
///
/// This attribute disables [type-based special behavior](crate::derive::doc_special_types)
/// for the current field.
///
///
/// [`no_impl_default`]: crate::derive::doc_ref_attrs#tmeta:no_impl_default
/// [`no_impl_deserialize`]: crate::derive::doc_ref_attrs#tmeta:no_impl_deserialize
/// [`default`]: crate::derive::doc_ref_attrs#fmeta:default_default
/// [`default =`]: crate::derive::doc_ref_attrs#fmeta:default_equals
/// [`no_default`]: crate::derive::doc_ref_attrs#fmeta:no_default
/// [`build`]: crate::derive::doc_ref_attrs#fmeta:build
/// [`try_build`]: crate::derive::doc_ref_attrs#fmeta:try_build
/// [`sub_builder`]: crate::derive::doc_ref_attrs#fmeta:sub_builder
/// [`setter(skip)`]: crate::derive::doc_ref_attrs#fmeta:setter_skip
/// [`serde`]:  crate::derive::doc_ref_attrs#fmeta:serde
pub mod doc_ref_attrs {}

/// Differences from `derive_builder`
///
/// * Not all derive_builder attributes have been cloned: only the ones that we used.
/// * Attributes have been adjusted where possible to be easier to use.
/// * It is not necessary to use `impl_standard_builder!`
/// * The appropriate `serde` attributes are automatically provided on the builder.
/// * Every field must have some default behavior specified, or must have the `no_default` option given.
///   (With `derive_builder`, `no_default` is the default, which can result in confusing test failures.)
/// * Sub-builders are supported.
/// * The `cfg` attribute can be used to warn when the user
///   tries to provide a value for an compiled-out field.
/// * There is (limited) support for generics.
/// * The generated documentation is a little better.
pub mod doc_differences {}

/// Types with special handling
///
/// The `derive_deftly(TorConfig)` macro currently has special handling for a few types.
///
/// To override the special handling for a field, use the `TorConfig(no_magic)`
/// attribute on that field.
///
/// <!-- TODO: Document type requirements in general, and rename this to doc_cfg_types
/// or something like that. -->
///
/// > I don't like the behavior this feature,
/// > and I'm likely to change this entirely before I merge,
/// > but I'm documenting it anyway for comment.
/// >
/// > What I *do* want is the ability for us to ensure that correct,
/// > uniform behavior is (by default) generated for fields of the same type.
/// > In other words, I don't want to have to remember to set strip_option on every option,
/// > or to use humantime_serde on every duration,
/// > or to do the ListBuilder rigamaole on every Vec.
///
/// These types are handled on a best-effort basis by matching their names.
/// If you define a field to have another type that is an alias one of these,
/// we won't be able to detect and handle it.
///
/// The types with special handling are:
///
/// ## `String`
///
/// The setter for each [`String`] field takes `impl AsRef<str>` as its argument.
///
/// ## `NonZero<T>`
///
/// The setter for a [`NonZero`](std::num::NonZero)`<T>` field takes `T` as its argument.
/// When the build() function is called, it returns an error if the provided
/// value was zero.
///
/// ## `Duration`
///
/// The serde implementations for a [`Duration`](std::time::Duration) field
/// use [`humantime_serde`] to accept and generate human-readable strings.
pub mod doc_special_types {}

// Future work: (TODO)
//
// Before stabilization:
//
// - Replace "magic" type handling.
//   Current magic types are nonzero, string, and duration, but I want to support
//   option and vec at the least.
//   - With vec:
//     - Include list_builder_accessors
//     - require that list be empty
// - Decide whether to replace TorConfig with tor_config as our attr namespace id.
// - Possibly, accept pre_build as a synonym for validate.
// - Add a field(skip).
// - Can I replace cfg() with a single FeatureNotSupported type, or a family of such types?
// - derive-deftly#109 would let us have better syntax for tmeta:attr, fmeta:attr, and fmeta:serde.

// Needed for fs-mistrust:
// - Override "build" error type.
//
// Couldn't figure out, maybe not needed.
// - Derive publisher_view as needed
// - Derive Flattenable?
//

use derive_deftly::define_derive_deftly;

/// Values used by the TorConfig derive_deftly template.
#[doc(hidden)]
pub mod exports {
    pub use super::{
        bld_magic_cvt, bld_magic_setter_arg_type, bld_magic_setter_cvt, bld_magic_type,
        normalize_and_invoke, strip_option,
    };
    pub use crate::{ConfigBuildError, impl_standard_builder, load::Builder as BuilderTrait};
    pub use figment;
    pub use humantime_serde;
    pub use serde::{Deserialize, Deserializer, Serialize, Serializer};
    pub use std::{
        clone::Clone,
        convert::{AsRef, Into, TryInto},
        default::Default,
        fmt::Debug,
        option::Option,
        result::Result,
    };
    pub use toml;
    pub use tracing;
    pub use void;
}

/// Module to import in order to use the TorConfig template.
pub mod prelude {
    pub use super::derive_deftly_template_TorConfig;
}

/// Helper to implement `strip_option`: Takes a single argument whose type is
#[doc(hidden)]
#[macro_export]
macro_rules! strip_option {
    { $($($(::)? std::)? option::)? Option $(::)? < $t:ty >  } => { $t };
    { $t:ty } => { compile_error!{"'strip_option' only works on a type that is an Option<X>"} }
}
pub use strip_option;

/// Helper: Takes a @command name, a {type}, and a list of arguments.
/// Determines which macro corresponds to the type,
/// and invokes that macro with arguments: @command {type} args.
///
/// The macros corresponding to types are [`string_typemagic`] for `String`,
/// [`nonzero_typemagic`] for `NonZero*`,
/// and [`no_typemagic`] for everything else.
///
/// Recognized @commands are:
///  - `@build_type {ty}` - The type that should be used as `T` for the builder field's `Option<T>`.
///  - `@setter_arg_type {ty}` - The type that the setter should take as an argument.
///  - `@setter_cvt {ty} {e}`- Code to run inside the setter to convert {e} into a `@build_type {ty}`
///  - `@build_field {ty} {e} {name}` - Code to convert `@build_type {ty}` into {ty}.  Uses the
///    field name `{fname}` to generate errors.
#[doc(hidden)]
#[macro_export]
macro_rules! normalize_and_invoke {
  //  { @$cmd:ident {$( $($(::)? std::)? option:: )? Option $(::)? <$t:ty>}  $($args:tt)*} => { $crate::option_typemagic! { @$cmd {$t} $($args)* } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZero $(::)? < $t:ty >}  $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {$t} $($args)* } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZeroU8}                 $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {u8}   $($args)* } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZeroU16}                $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {u16}  $($args)*  } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZeroU32}                $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {u32}  $($args)*  } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZeroU64}                $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {u64}  $($args)*  } };
    { @$cmd:ident {$( $($(::)? std::)? num:: )? NonZeroU128}               $($args:tt)*} => { $crate::derive::nonzero_typemagic!{ @$cmd {u128} $($args)*  } };
    { @$cmd:ident {$( $($(::)? std::)? string:: )? String}                 $($args:tt)*} => { $crate::derive::string_typemagic! { @$cmd $($args)* } };
    { @$cmd:ident {$($t:tt)+}                                              $($args:tt)*} => { $crate::derive::no_typemagic!     { @$cmd {$($t)+} $($args)* } };
}
pub use normalize_and_invoke;

/// Implement type magic for types that aren't special.
///
/// See [`normalize_and_invoke`] for details.
#[doc(hidden)]
#[macro_export]
macro_rules! no_typemagic {
    { @build_type {$t:ty} } => { $t };
    { @setter_arg_type {$t:ty}} => { $t };
    { @setter_cvt {$t:ty} {$e:expr} } => { $e };
    { @build_field {$t:ty} {$e:expr} {$fname:expr}} => { $e.clone() };
}
pub use no_typemagic;

/// Implement type magic for `String`.
///
/// See [`normalize_and_invoke`] for details.
#[macro_export]
macro_rules! string_typemagic {
    { @build_type } => { String };
    { @setter_arg_type } => { impl $crate::derive::exports::AsRef<str> };
    { @setter_cvt {$e:expr} } => { $e.as_ref().to_string() };
    { @build_field {$e:expr} {$fname:expr}} => { $e.clone() };
}
pub use string_typemagic;

/// Implement type magic for `NonZero*`.
///
/// See [`normalize_and_invoke`] for details.
#[doc(hidden)]
#[macro_export]
macro_rules! nonzero_typemagic {
    { @build_type {$t:ty} } => { $t };
    { @setter_arg_type {$t:ty} } => { $t };
    { @setter_cvt {$t:ty} {$e:expr} } => { $e };
    { @build_field {$t:ty} {$e:expr} {$fname:expr}} => {
        $e.map(|v|
            v.try_into().map_err(|_| $crate::ConfigBuildError::Invalid {
                field: $fname.to_string(),
                problem: "value not allowed to be zero".to_string()
        })).transpose()?
    }
}
pub use nonzero_typemagic;

/*
// This doesn't work, and is making me rethink all of the magic.

#[macro_export]
macro_rules! option_typemagic {
    { @build_type {$t:ty} } => { ::std::option::Option<$t> };
    { @setter_arg_type {$t:tt}} => { impl $crate::derive::SetterArgument<
        $crate::derive::bld_magic_setter_arg_type!{$t}
    > };
    { @setter_cvt {$t:ty} {$e:expr} } => {
        $crate::derive::bld_magic_setter_cvt!{
            { $crate::derive::SetterArgument::to_ref(&$e).cloned() }
            { $t }
        }
    };
    { @build_field {$t:ty} {$e:expr} {$fname:expr}} => { $e.clone() };
}
    */

/// Helper: Expand to the type `T` that a field of type `{$t}`
/// should have in the builder struct's Option<T>.
#[doc(hidden)]
#[macro_export]
macro_rules! bld_magic_type {
    { $($t:tt)+ } => { $crate::derive::normalize_and_invoke!{ @build_type {$($t)+} } };
}
pub use bld_magic_type;

/// Helper: Expand to the type `T` that a setter should take for a field of type `{$t}`
#[doc(hidden)]
#[macro_export]
macro_rules! bld_magic_setter_arg_type {
    { $($t:tt)+ } => { $crate::derive::normalize_and_invoke!{ @setter_arg_type {$($t)+} } };
}
pub use bld_magic_setter_arg_type;

/// Helper: Expand to the code that should be used to convert `{e}` into the type
/// `bld_magic_type!{$t}`.
#[doc(hidden)]
#[macro_export]
macro_rules! bld_magic_setter_cvt {
    { {$e:expr} {$($t:tt)+}} => { $crate::derive::normalize_and_invoke!{ @setter_cvt {$($t)+} {$e} } };
}
pub use bld_magic_setter_cvt;

/// Helper: Expand to the code that should be used to convert `{e}` from type
/// `bld_magic_type!{$t}` into $t.  Uses the field name `{fname} to generate errors.
#[doc(hidden)]
#[macro_export]
macro_rules! bld_magic_cvt {
    { {$e:expr} {$fname:expr} {$($t:tt)+}} => { $crate::derive::normalize_and_invoke!{ @build_field {$($t)+} {$e} {$fname} } };
}
pub use bld_magic_cvt;

define_derive_deftly! {
    /// Define a builder type for a given type, with settings appropriate to participate in the Arti
    /// build system.
    ///
    /// See [module documentation](crate::derive) for more information and usage instructions.
    export TorConfig beta_deftly, for struct:

    // -------------------
    // Common definitions and aliases.

    // Location of exports for this macro.
    ${define E {$crate::derive::exports}}

    // Location of exports for this macro, as a string.
    //
    // TODO $crate: I would prefer to use ${concat $crate "::derive::exports"} instead,
    // but d-d doesn't accept that. See
    // https://gitlab.torproject.org/Diziet/rust-derive-deftly/-/issues/132
    ${define EX ${concat "tor_config::derive::exports"}}

    // Current field name as string.
    ${define FNAME { ${concat $fname} }}

    /// Name of the build method.
    ${define BLD_NAME {
        ${tmeta(TorConfig(build_fn(name))) as ident, default build}
    } }

    // -------------------
    // Definitions and aliases for defining the builder struct.

    // True if the field type appears to be `std::time::Duration`
    //
    // (This can't be done with the regular "magic" macro system,
    // since it needs to be used in expansions that produce a field attribute.
    // macro_rules! macros can't appear in a field-attribute position.
    // There _are_ workarounds here, which I'll consider while
    // reafactoring the magic system.)
    ${defcond F_IS_DURATION
        any(approx_equal({$ftype}, {Duration}),
            approx_equal({$ftype}, {time::Duration}),
            approx_equal({$ftype}, {std::time::Duration}),
            approx_equal({$ftype}, {::std::time::Duration}))
    }

    // Condition: True unless Serialize and Deserialize have both been disabled.
    ${defcond SERDE
        not(all(tmeta(TorConfig(no_impl_serialize)),
                tmeta(TorConfig(no_impl_deserialize))))
    }

    // Expands to any attributes that should be applied to the current builder field
    // based on magic type behavior.
    ${define BLD_MAGIC_ATTRIBUTES
        ${if fmeta(TorConfig(no_magic)) {
        } else {
            ${select1
            F_IS_DURATION {
                ${if SERDE {
                    #[serde(with = ${concat $EX "::humantime_serde::option"})]
                }}
            } else {
                // No magic needed.
            }}
        }}
    }
    // Expands to $ftype of the current builder field, as modified by type magic.
    // (Most everybody should use $BLD_FTYPE instead.)
    ${define BLD_MAGIC_FTYPE {
        ${if fmeta(TorConfig(no_magic)) {
            $ftype
        } else {
            $E::bld_magic_type!($ftype)
        }}
    }}
    // Expands to the type of the field within the builder.
    ${define BLD_FTYPE {
        ${if fmeta(TorConfig(field(ty))) {
            ${fmeta(TorConfig(field(ty))) as ty}
        } else if fmeta(TorConfig(sub_builder)) {
            $< $ftype Builder >
        } else {
            $E::Option<$BLD_MAGIC_FTYPE>
        }}
    }}

    /// If the current field is conditionally present, expands to the `cfg`
    /// attribute we should apply to it.
    ${define IF_CFG {
        // TODO: Infelicity: It would be nice if this didn't have to take "cfg" as a string.
        ${if fmeta(TorConfig(cfg)) {
            #[cfg( ${fmeta(TorConfig(cfg)) as token_stream} )]
        }}
    }}


    // Visibility for the builder type.
    ${define BLD_TVIS
        ${tmeta(TorConfig(vis)) as token_stream, default $tvis}
    }

    // Visibility for the current field in the builder type.
    ${define BLD_FVIS
        ${fmeta(TorConfig(field(vis))) as token_stream, default {} }
    }

    // -------------------
    // Define the builder type.

    #[doc = ${concat "A builder to create an instance of [`" $tname "`].\n"}]
    #[derive($E::Default, $E::Clone, $E::Debug)]
    ${if not(tmeta(TorConfig(no_impl_deserialize))) {
        #[derive($E::Deserialize)]
    }}
    ${if not(tmeta(TorConfig(no_impl_serialize))) {
        #[derive($E::Serialize)]
    }}
    ${ if tmeta(TorConfig(attr)) {
        #[ ${tmeta(TorConfig(attr)) as token_stream} ]
    }}
    #[allow(dead_code)]
    $BLD_TVIS $tdefkwd $<$tname Builder><$tdefgens>
    where $twheres
    {
        $(
            ${if fmeta(TorConfig(attr)) {
                #[${fmeta(TorConfig(attr)) as token_stream}]
            }}
            ${if SERDE {
                // TODO Is this truly necessary and desired for every field?
                #[serde(default)]
            }}
            ${ if fmeta(TorConfig(serde)) {
                #[ serde( ${fmeta(TorConfig(serde)) as token_stream} )]
            }}
            #[doc = ${concat "In-progress value for " $fname ".\n\n"
                             "See [`"$tname "#structfield." $fname "`]"}]
            $BLD_MAGIC_ATTRIBUTES
            $IF_CFG
            $BLD_FVIS ${fdefine $fname} $BLD_FTYPE,

            ${if all(SERDE, fmeta(TorConfig(cfg))) {
                /// Placeholder to catch attempts to use this field when
                /// disabled by configuration.
                #[cfg(not(${fmeta(TorConfig(cfg)) as token_stream} ))]
                #[serde(default)]
                ${fdefine $fname} $E::Option<$E::toml::Value>,
            }}
        )
    }

    // -------------------
    // Definitions to implement setter/accessor methods.

    // Expands to the name of the setter/accessor for the current field.
    ${define SETTER_NAME { ${fmeta(TorConfig(setter(name))) as ident, default $fname} }}

    // Expands the declared type that the setter should take as its argument.
    ${define SETTER_INPUT_TYPE {
        ${select1
            fmeta(TorConfig(setter(into))) {
                impl $E::Into<$ftype>
            }
            fmeta(TorConfig(setter(try_into))) {
                SetterArg
            }
            fmeta(TorConfig(setter(strip_option))) {
                $E::strip_option!{$ftype}
            }
            else {
                ${if fmeta(TorConfig(no_magic)) {
                    $ftype
                } else {
                    $E::bld_magic_setter_arg_type!{$ftype}
                }
            }}
        }}}

    // Expands to the generics (if any) that the setter should take.
    ${define SETTER_GENS {
        ${if fmeta(TorConfig(setter(try_into))) {
            <SetterArg : $E::TryInto<$ftype>>
        } else {
        }}
    }}

    // Expands to the expression that the setter should return.
    ${define SETTER_RETURN {
        ${if fmeta(TorConfig(setter(try_into))) {
            Ok(self)
        } else {
            self
        }}
    }}

    // Expands to the declared return type of the setter.
    ${define SETTER_RETURN_TYPE {
        ${if fmeta(TorConfig(setter(try_into))) {
            $E::Result<&mut Self, SetterArg::Error>
        } else {
            &mut Self
        }}
    }}

    // Expands to a string that we should add to the documentation
    // to explain the default value of the current field.
    ${define DFLT_DOC {
        ${select1
            fmeta(TorConfig(sub_builder)) { "" }
            // TODO: Say _something_ here if we can.
            fmeta(TorConfig(build)) { "" }
            fmeta(TorConfig(try_build)) { "" }
            fmeta(TorConfig(default)) {
                ${concat "If no value is provided for `" $fname "`, "
                  "[`build`](Self::build) will use `"
                  ${fmeta(default) as str, default "Default::default()"}
                  "`."
            }}
            fmeta(TorConfig(no_default)) {
                ${concat "If no value is provided for `" $fname "`, "
                  "[`build`](Self::build) will fail with an error."}
            }
        }
    }}

    // Expands to the visibility for the current setter/accessor.
    ${define SETTER_VIS {
        ${fmeta(TorConfig(setter(vis))) as token_stream, default $BLD_TVIS}
    }}

    // Expands to a definition of the setter function for the current field.
    ${define SET_FN {
        #[doc = ${concat "Provide a value for `" $fname "`.\n\n"}]
        #[doc = $DFLT_DOC]
        #[doc = ${concat "\n\n## " $fname "\n\n" }]
        ${fattrs doc}
        $IF_CFG
        $SETTER_VIS fn $SETTER_NAME $SETTER_GENS (&mut self, val: $SETTER_INPUT_TYPE) -> $SETTER_RETURN_TYPE {
            ${select1
                fmeta(TorConfig(setter(into))) {
                    self.$fname = Some(val.into());
                }
                fmeta(TorConfig(setter(try_into))) {
                    self.$fname = Some(val.try_into()?);
                }
                fmeta(TorConfig(setter(strip_option))) {
                    self.$fname = Some(Some(val));
                }
                else {
                    ${if fmeta(TorConfig(no_magic)) {
                        self.$fname = Some(val);
                    } else {
                        self.$fname = Some($E::bld_magic_setter_cvt!({val} {$ftype}));
                    }}
                }
            }
            $SETTER_RETURN
        }
  }}

    // Expands to a declaration for the sub-builder accessor function for the current field.
    ${define ACCESS_SUBBUILDER_FN {

        #[doc = ${concat "Return a mutable reference to the inner builder for `" $fname "`.\n\n"
                  "## " $fname "\n\n"
                }]
        ${fattrs doc}
        $IF_CFG
        $SETTER_VIS fn $fname(&mut self) -> &mut $<$ftype Builder> {
            &mut self.$fname
        }
    }}

    // -------------------
    // Define the setter/accessors methods.

    #[allow(dead_code)]
    impl<$tgens> $<$ttype Builder>
    where $twheres {

        $(
            ${if fmeta(TorConfig(setter(skip))) {
                // generate nothing.
            } else if fmeta(TorConfig(sub_builder)) {
                $ACCESS_SUBBUILDER_FN
            } else {
                $SET_FN
            }}
        )
    }

    // -------------------
    // Definitions and helpers for the build method.

    // Expands to the name of the function to use to build the sub-builder for the current field.
    ${define SUB_BUILDER_BUILD_FN {
        ${fmeta(TorConfig(sub_builder(build_fn))) as path, default build}
    }}

    // Expands to an expression of type Option<$ftype> for the current field,
    // taking type-based magic into account.
    ${define BLD_MAGIC_CVT {
        ${if fmeta(TorConfig(no_magic)) {
            self.$fname.clone()
        } else {
            $E::bld_magic_cvt!({self.$fname} {${concat $fname}} {$ftype})
        }}
    }}

    // Expands to an expression for building the current field,
    // and returning an appropriate error if there was a problem.
    ${define BUILD_FIELD {
         ${select1
            fmeta(TorConfig(sub_builder)) {
                self.$fname.$SUB_BUILDER_BUILD_FN().map_err(|e| e.within($FNAME))?
            }
            fmeta(TorConfig(default)) {
                $BLD_MAGIC_CVT.unwrap_or_else(
                    || ${fmeta(TorConfig(default)) as expr, default {Default::default()}})
            }
            fmeta(TorConfig(build)) {
                (${fmeta(TorConfig(build)) as expr})(self)
            }
            fmeta(TorConfig(try_build)) {
                (${fmeta(TorConfig(try_build)) as expr})(self)?
            }
            fmeta(TorConfig(no_default)) {
                $BLD_MAGIC_CVT.ok_or_else(
                    || $E::ConfigBuildError::MissingField { field: stringify!($fname).into() }
                )?
            }
            else {
                ${error "Every field must have default, no_default, try_build, build, or sub_builder."}
            }
        }
    }}

    // Expands to the visibility of the build method.
    ${define BLD_FN_VIS {
        ${tmeta(TorConfig(build_fn(vis))) as token_stream, default $BLD_TVIS}
    }}

    // -------------------
    // Define the build method and the new() method.

    #[allow(dead_code)]
    impl<$tgens> $<$ttype Builder>
    where $twheres {
        /// Return a new builder object.
        $BLD_TVIS fn new() -> Self {
            Self::default()
        }

        #[doc = ${concat
            "Try to construct a new [`" $tname "`] from the fields set in this builder.\n\n"
            "Return an error if any required field is missing, or is set to something invalid.\n"
        }]
        $BLD_FN_VIS fn $BLD_NAME(&self) -> $E::Result<$ttype, $E::ConfigBuildError> {
            // Call validate as appropriate.
            ${if tmeta(TorConfig(validate)) {
                let () = ${tmeta(TorConfig(validate)) as path}(self)?;
            }}

            // Warn if any configured-out option was provided.
            $(
                ${if fmeta(TorConfig(cfg)) {
                    #[cfg(not( ${fmeta(TorConfig(cfg)) as token_stream} ))]
                    if self.$fname.is_some() {
                        $E::tracing::warn!(
                            ${concat "Ignored configuration for '" $fname
                              "'. This option has no effect unless Arti is built with '"
                              ${fmeta(TorConfig(cfg)) as str} "'"}
                        )
                    }
                }}
            )

            // Construct the configuration struct.
            let result = $tname {
                $(
                    $IF_CFG
                    $fname: $BUILD_FIELD ,

                    ${if fmeta(TorConfig(cfg)) {
                        #[cfg(not( ${fmeta(TorConfig(cfg)) as token_stream} ))]
                        $fname: $E::Default::default(),
                    }}
                )
            };

            // Call the post_build function to transform the result.
            ${if tmeta(TorConfig(post_build)) {
                let result = ${tmeta(TorConfig(post_build)) as path}(result)?;
            }}

            Ok(result)
        }
    }

    // -------------------
    // Add a builder() method to the configuration type.
    impl<$tgens> $ttype
    where $twheres {
        #[doc = ${concat "Return a new [`" $tname " Builder`] to construct an instance of this type."}]
        #[allow(dead_code)]
        $tvis fn builder() -> $<$ttype Builder> {
            $<$ttype Builder>::default()
        }
    }

    // -------------------
    // Implement `$crate::Builder` for the Builder type.

    ${if not(tmeta(TorConfig(no_impl_builder_trait))) {
        impl<$tgens> $E::BuilderTrait for $<$ttype Builder>
        where $twheres {
            type Built = $ttype;
            fn build(&self) -> $E::Result<$ttype, $E::ConfigBuildError> {
                $<$ttype Builder>::$BLD_NAME(self)
            }
        }
    }}

    // -------------------
    // Implement `Default` for the configuration type, in terms of the Builder.
    // (Unless the no_impl_default attribute was present.)

    ${if not(tmeta(TorConfig(no_impl_default))) {
        impl<$tgens> $E::Default for $ttype
        where $twheres {
            fn default() -> Self {
                // It's okay to use unwrap; one of the test cases verifies it.
                $<$ttype Builder>::default().$BLD_NAME().unwrap()
            }
        }
    }}

    // ------------------
    // Test module for the builder.
    ${if not(any(
        tmeta(TorConfig(no_impl_default)),
        tmeta(TorConfig(no_impl_deserialize)),
        tmeta(TorConfig(no_test_default))))
        {
        #[cfg(test)]
        mod $<test_ ${snake_case $tname} _builder> {
            #[test]
            // TODO: Doesn't work on generics. Do we care?
            fn test_impl_default() {
                let def = super::$ttype::default();
                let empty_config = $E::figment::Figment::new();
                let builder: super::$<$ttype Builder> = empty_config.extract().unwrap();
                let from_empty = builder.$BLD_NAME().unwrap();
                assert_eq!(def, from_empty);
            }
        }
    }}
}
pub use derive_deftly_template_TorConfig;

#[cfg(test)]
mod test {
    // @@ begin test lint list maintained by maint/add_warning @@
    #![allow(clippy::bool_assert_comparison)]
    #![allow(clippy::clone_on_copy)]
    #![allow(clippy::dbg_macro)]
    #![allow(clippy::mixed_attributes_style)]
    #![allow(clippy::print_stderr)]
    #![allow(clippy::print_stdout)]
    #![allow(clippy::single_char_pattern)]
    #![allow(clippy::unwrap_used)]
    #![allow(clippy::unchecked_time_subtraction)]
    #![allow(clippy::useless_vec)]
    #![allow(clippy::needless_pass_by_value)]
    //! <!-- @@ end test lint list maintained by maint/add_warning @@ -->

    use crate::ConfigBuildError;
    use assert_matches::assert_matches;
    use tracing_test::traced_test;

    /// Separate module to put config structs and their builders in, so that they aren't
    /// able to pick up anything we don't deliberately import.
    mod t {
        use std::{
            num::{NonZero, NonZeroU8},
            time::Duration,
        };

        // TODO: I wish this weren't necessary, but we can't use $crate inside CONCAT.
        // See "TODO $crate" note above.
        use crate as tor_config;

        use crate::derive::prelude::*;
        use derive_deftly::Deftly;

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct Simple {
            #[deftly(TorConfig(default))]
            pub(super) xyz: u32,

            #[deftly(TorConfig(default = "3"))]
            pub(super) abc: u16,

            #[deftly(TorConfig(build = "|_self| 6 * 7"))]
            pub(super) forty_two: u16,

            #[deftly(TorConfig(try_build = "|_self| Ok::<_,crate::ConfigBuildError>(6 * 7 + 1)"))]
            pub(super) forty_three: u16,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(no_impl_default))]
        pub(super) struct FieldNoDefault {
            #[deftly(TorConfig(default))]
            pub(super) has_default: u32,
            #[deftly(TorConfig(no_default))]
            pub(super) has_no_default: u32,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(no_impl_default))]
        pub(super) struct Sub {
            #[deftly(TorConfig(sub_builder))]
            pub(super) simple: Simple,

            #[deftly(TorConfig(sub_builder))]
            pub(super) fnd: FieldNoDefault,

            #[deftly(TorConfig(default))]
            pub(super) s: String,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct Magic {
            #[deftly(TorConfig(default = "nz(7)"))]
            pub(super) nzu8: NonZeroU8,

            #[deftly(TorConfig(default = "nz(123)"))]
            pub(super) nzu8_2: NonZero<u8>,

            #[deftly(TorConfig(default))]
            pub(super) dur: Duration,

            #[deftly(TorConfig(default))]
            pub(super) s: String,
        }

        fn nz(x: u8) -> NonZeroU8 {
            x.try_into().unwrap()
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct CfgEnabled {
            #[deftly(TorConfig(default, cfg = "true"))]
            pub(super) enabled: u32,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct CfgDisabled {
            #[deftly(TorConfig(default, cfg = "false"))]
            pub(super) disabled: u32,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(
            validate = "Self::check_odd",
            post_build = "CfgValidating::check_even"
        ))]
        pub(super) struct CfgValidating {
            #[deftly(TorConfig(default = "1"))]
            pub(super) odd: u32,
            #[deftly(TorConfig(default))]
            pub(super) even: u32,
        }
        impl CfgValidatingBuilder {
            fn check_odd(&self) -> Result<(), crate::ConfigBuildError> {
                if let Some(v) = self.odd {
                    if v & 1 != 1 {
                        return Err(crate::ConfigBuildError::Invalid {
                            field: "odd".to_string(),
                            problem: "Not odd".to_string(),
                        });
                    }
                }
                Ok(())
            }
        }
        impl CfgValidating {
            fn check_even(self) -> Result<Self, crate::ConfigBuildError> {
                if self.even & 1 != 0 {
                    return Err(crate::ConfigBuildError::Invalid {
                        field: "even".to_string(),
                        problem: "Not even".to_string(),
                    });
                }
                Ok(self)
            }
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(no_impl_serialize, no_test_default))]
        pub(super) struct CfgGeneric<T, U>
        where
            T: Clone + std::fmt::Debug + PartialEq + Default,
            U: Clone + std::fmt::Debug + PartialEq + Default,
        {
            #[deftly(TorConfig(default, no_magic))]
            pub(super) t: T,
            #[deftly(TorConfig(default, no_magic))]
            pub(super) u: U,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct OptionsCfg {
            #[deftly(TorConfig(default))]
            pub(super) a: Option<u32>,
            #[deftly(TorConfig(default = "Some(123)"))]
            pub(super) b: Option<u32>,
            #[deftly(TorConfig(default = "Some(nz(42))"))]
            pub(super) nz: Option<NonZeroU8>,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(attr = "derive(Eq,Ord,PartialOrd,PartialEq)"))]
        pub(super) struct AttribsCfg {
            #[deftly(TorConfig(default))]
            #[deftly(TorConfig(attr = r#"serde(alias = "fun_with_numbers")"#))]
            #[deftly(TorConfig(serde = r#"alias = "its_fun_to_count""#))]
            pub(super) a: u32,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct SettersCfg {
            #[deftly(TorConfig(default, setter(skip)))]
            pub(super) a: u32,

            #[deftly(TorConfig(default, setter(into)))]
            pub(super) b: u32,

            #[deftly(TorConfig(default, setter(try_into)))]
            pub(super) c: u32,
            #[deftly(TorConfig(default, setter(strip_option)))]
            pub(super) d: Option<u32>,
            #[deftly(TorConfig(default, setter(name = "set_the_e")))]
            pub(super) e: u32,
        }
        impl SettersCfgBuilder {
            // Custom setter.
            pub(super) fn a(&mut self, val: u32) {
                self.a = Some(val * 2);
            }
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(no_impl_serialize, no_impl_deserialize))]
        pub(super) struct NoSerdeCfg {
            #[deftly(TorConfig(default))]
            pub(super) ip: u128,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        #[deftly(TorConfig(build_fn(name = "build_this")))]
        pub(super) struct RenameBuild {
            #[deftly(TorConfig(default))]
            pub(super) member: u16,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct RenameSubBuild {
            #[deftly(TorConfig(sub_builder(build_fn = "build_this")))]
            pub(super) inner: RenameBuild,
        }

        #[derive(Deftly, Clone, Debug, PartialEq)]
        #[derive_deftly(TorConfig)]
        pub(super) struct FullyCustom {
            #[deftly(TorConfig(
                setter(skip),
                field(ty = "(u32, u32)", vis = "pub(super)"),
                build = r#"|this: &Self| format!("{} {}", this.value.0, this.value.1)"#,
            ))]
            pub(super) value: String,
        }
        impl FullyCustomBuilder {
            pub(super) fn try_the_thing(&mut self, x: u64) {
                self.value = ((x >> 32) as u32, x as u32);
            }
        }
    }

    #[test]
    fn test_simple_defaults() {
        let b = t::SimpleBuilder::new();
        let x = b.build().unwrap();
        assert_eq!(x.xyz, 0);
        assert_eq!(x.abc, 3);
        assert_eq!(x.forty_two, 42);
        assert_eq!(x.forty_three, 43);
    }

    #[test]
    fn test_simple_setters() {
        let mut b = t::SimpleBuilder::new();
        let x = b.abc(7).xyz(77).forty_two(777).build().unwrap();
        assert_eq!(x.xyz, 77);
        assert_eq!(x.abc, 7);
        assert_eq!(x.forty_two, 42);
        assert_eq!(x.forty_three, 43);
    }

    #[test]
    fn test_simple_serde() {
        let v = r#"
        xyz = 7
        "#;
        let b: t::SimpleBuilder = toml::from_str(v).unwrap();
        let x = b.build().unwrap();
        assert_eq!(x.xyz, 7);
        assert_eq!(x.abc, 3);
        assert_eq!(x.forty_two, 42);
        assert_eq!(x.forty_three, 43);
    }

    #[test]
    fn test_field_no_default() {
        let e = t::FieldNoDefaultBuilder::new().build().unwrap_err();
        assert_matches!(
            e,
            ConfigBuildError::MissingField {
                field
            } if field == "has_no_default"
        );
        let v = t::FieldNoDefaultBuilder::new()
            .has_no_default(42)
            .build()
            .unwrap();
        assert_eq!(v.has_default, 0);
        assert_eq!(v.has_no_default, 42);
    }

    #[test]
    fn test_subbuilder() {
        let e = t::SubBuilder::new().build().unwrap_err();
        assert_matches!(
            e,
            ConfigBuildError::MissingField {
                field
            } if field == "fnd.has_no_default"
        );

        let mut b = t::SubBuilder::new();
        b.fnd().has_no_default(5).has_default(66);
        b.simple().abc(123);
        b.s("Hello");
        let v = b.build().unwrap();
        assert_eq!(v.fnd.has_no_default, 5);
        assert_eq!(v.fnd.has_default, 66);
        assert_eq!(v.simple.abc, 123);
        assert_eq!(v.simple.xyz, 0);
        assert_eq!(v.s, "Hello");
    }

    #[test]
    fn test_subbuilder_serde() {
        let v = r#"
        s = "hello world"
        [fnd]
        has_no_default = 1234
        "#;
        let b: t::SubBuilder = toml::from_str(v).unwrap();
        let x = b.build().unwrap();
        assert_eq!(x.fnd.has_no_default, 1234);
        assert_eq!(x.fnd.has_default, 0);
        assert_eq!(x.s, "hello world");
    }

    #[test]
    fn test_magic_nz() {
        let mut b = t::Magic::builder();
        b.nzu8(123);
        b.nzu8_2(1);
        let v = b.build().unwrap();
        assert_eq!(v.nzu8.get(), 123);
        assert_eq!(v.nzu8_2.get(), 1);

        let e = t::MagicBuilder::new().nzu8(0).build().unwrap_err();
        let ConfigBuildError::Invalid { field, problem } = e else {
            panic!("Error not as expected ({e:?})");
        };
        assert_eq!(field, "nzu8");
        assert_eq!(problem, "value not allowed to be zero");

        let e = t::MagicBuilder::new().nzu8_2(0).build().unwrap_err();
        let ConfigBuildError::Invalid { field, problem } = e else {
            panic!("Error not as expected ({e:?})");
        };
        assert_eq!(field, "nzu8_2");
        assert_eq!(problem, "value not allowed to be zero");
    }

    #[test]
    fn test_magic_string() {
        let mut b = t::Magic::builder();
        b.s("hello"); // <-- note that this is not a String.
        let v = b.build().unwrap();
        assert_eq!(v.s, "hello");

        #[allow(clippy::unnecessary_to_owned)]
        b.s("world".to_string());
        let v = b.build().unwrap();
        assert_eq!(v.s, "world");

        struct AsRefDemo;
        impl AsRef<str> for AsRefDemo {
            fn as_ref(&self) -> &str {
                "this is a string too"
            }
        }

        b.s(AsRefDemo);
        let v = b.build().unwrap();
        assert_eq!(v.s, "this is a string too");
    }

    #[test]
    fn test_magic_duration() {
        let v = r#"
        dur = "1 hour"
        "#;
        let b: t::MagicBuilder = toml::from_str(v).unwrap();
        let x = b.build().unwrap();
        assert_eq!(x.dur, std::time::Duration::new(60 * 60, 0));
    }

    #[test]
    #[traced_test]
    fn test_cfg_enabled() {
        let s = r#"
        enabled = 12
        "#;
        let b: t::CfgEnabledBuilder = toml::from_str(s).unwrap();
        let v = b.build().unwrap();
        assert_eq!(v.enabled, 12);
        assert!(!logs_contain("no effect"));
    }

    #[test]
    #[traced_test]
    fn test_cfg_disabled() {
        let s = r#"
        disabled = "hello world"
        "#;
        let b: t::CfgDisabledBuilder = toml::from_str(s).unwrap();
        let v = b.build().unwrap();
        assert_eq!(v.disabled, 0);
        assert!(logs_contain(
            "Ignored configuration for 'disabled'. This option has no effect unless Arti is built with 'false'"
        ));
    }

    #[test]
    fn test_validating() {
        let err_notodd = t::CfgValidating::builder().odd(6).build().unwrap_err();
        assert_eq!(
            err_notodd.to_string(),
            "Value of odd was incorrect: Not odd"
        );
        let err_noteven = t::CfgValidating::builder().even(5).build().unwrap_err();
        assert_eq!(
            err_noteven.to_string(),
            "Value of even was incorrect: Not even"
        );
        let v = t::CfgValidating::builder().odd(5).even(6).build().unwrap();
        assert_eq!(v.odd, 5);
        assert_eq!(v.even, 6);
    }

    #[test]
    fn test_generic() {
        let mut b = t::CfgGeneric::<String, Vec<u32>>::builder();
        b.t("This is a test".to_string());
        b.u(vec![1, 2, 3]);
        let v = b.build().unwrap();
        assert_eq!(v.t, "This is a test");
        assert_eq!(&v.u, &[1, 2, 3]);
    }

    #[test]
    fn test_attributes() {
        let s1 = "fun_with_numbers = 1982374";
        let s2 = "its_fun_to_count = 1982375";
        let b1: t::AttribsCfgBuilder = toml::from_str(s1).unwrap();
        let b2: t::AttribsCfgBuilder = toml::from_str(s2).unwrap();
        // Make sure that derive(PartialEq, Ord) happened.
        assert_eq!(b1, b1);
        assert_ne!(b1, b2);
        assert!(b1 < b2);
    }

    #[test]
    fn test_setter_meta() {
        let mut b = t::SettersCfgBuilder::new();
        b.a(7);
        b.b(5_u8);
        assert!(b.c(1_u64 << 40).is_err());
        b.c(100_u64).unwrap();
        b.d(19);
        b.set_the_e(22);
        let v = b.build().unwrap();
        assert_eq!(v.a, 7 * 2);
        assert_eq!(v.b, 5_u32);
        assert_eq!(v.c, 100_u32);
        assert_eq!(v.d, Some(19));
        assert_eq!(v.e, 22);
    }

    #[test]
    fn test_build_fn_rename() {
        let mut b = t::RenameBuild::builder();
        let v = b.member(6).build_this().unwrap();
        assert_eq!(v.member, 6);

        let mut b = t::RenameSubBuild::builder();
        b.inner().member(5);
        let v = b.build().unwrap();
        assert_eq!(v.inner.member, 5);
    }

    #[test]
    fn test_custom() {
        let mut b = t::FullyCustomBuilder::new();
        b.try_the_thing(0xF00B00B512345678);
        assert_eq!(b.value, (0xF00B00B5, 0x12345678));
        let v = b.build().unwrap();

        assert_eq!(v.value, "4027252917 305419896");
    }
}
