#!/usr/bin/env python3

import argparse
import time
import sys
import os.path
import os
import list_crates
from subprocess import run

TOPDIR = os.path.split(os.path.dirname(sys.argv[0]))[0]
os.chdir(TOPDIR)

supplementary_targets = dict()


def combination(*args):
    res = None
    for featureset in args:
        powerset = [[]]
        for feature in featureset:
            powerset.extend([combination + [feature] for combination in powerset])
        # remove empty set
        powerset.pop(0)
        if res is None:
            res = powerset
        else:
            new_res = []
            for prev_feat in res:
                for new_feat in powerset:
                    new_res.append(prev_feat + new_feat)
            res = new_res
    return res


supplementary_targets["tor-rtcompat"] = combination(
    ["async-std", "tokio", "native-tls", "rustls"]
)
supplementary_targets["arti-client"] = combination(
    ["async-std", "tokio", "native-tls", "rustls"]
)
supplementary_targets["arti"] = combination(
    ["async-std", "tokio"], ["native-tls", "rustls"]
)


def run_cmd(cmd, env=None):
    print("running:", " ".join(cmd), file=sys.stderr)
    p = run(cmd, env=env)
    if p.returncode != 0:
        raise Exception(f"Cargo command failed: {' '.join(cmd)}")


def test_crate(crate):
    # cargo check with various features

    run_cmd(["cargo", "--locked", "check", "-p", crate.name])
    run_cmd(
        [
            "cargo",
            "--locked",
            "check",
            "-p",
            crate.name,
            "--no-default-features",
            "--features",
            "full",
        ]
    )
    run_cmd(["cargo", "--locked", "check", "-p", crate.name, "--all-features"])

    for combination in supplementary_targets.get(crate.name, []):
        run_cmd(
            [
                "cargo",
                "--locked",
                "check",
                "-p",
                crate.name,
                "--no-default-features",
                "--features",
                ",".join(combination),
            ]
        )
    # TODO test random combination?

    # cargo test with default features

    run_cmd(["cargo", "--locked", "test", "-p", crate.name, "--all-targets"])

    # cargo test with minimal features

    conditional_options = []

    for line in open(crate.subdir + "/Cargo.toml"):
        conditional_option_directive = "# @@ test-all-crates conditional-option "
        # One option per line, so it can contain spaces
        if line.startswith(conditional_option_directive):
            (key, option) = (
                line[len(conditional_option_directive) :].rstrip().split(maxsplit=1)
            )
            if key == "minimal":
                conditional_options.append(option)
            continue

    env = os.environ.copy()
    env["RUSTFLAGS"] = f"{env.get('RUSTFLAGS', '')} --cfg arti_features_precise"
    run_cmd(
        [
            "cargo",
            "--locked",
            "test",
            "-p",
            crate.name,
            "--no-default-features",
            "--all-targets",
        ]
        + conditional_options,
        env=env,
    )


# https://stackoverflow.com/questions/24483182/python-split-list-into-n-chunks
def chunks(lst, n):
    """
    Yield n number of chunks from lst.

    This is a striped chunk, meaning that rather than making contiguous chunks, each chunk is made
    up of elements that are n spaces apart in the input list. This has the advantage of making
    sure that the lists are as close to evenly sized as possible, even if the input list length is
    not divisible by n.
    """
    for i in range(0, n):
        yield lst[i::n]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--parallel",
        type=str,
        default="1,0",
        help="Split the checking into multiple chunks and run only a single one of the chunks. "
        "Takes two comma-separated integers, the first is the number of chunks, "
        "the second is which chunk to run (zero-indexed)."
        "This assumes that the set of crates that exist is the same between all invocations.",
    )
    args = parser.parse_args()
    parallel_chunks, parallel_n = map(int, args.parallel.split(","))
    assert parallel_n < parallel_chunks

    crates = sorted(list_crates.list_crates(), key=lambda crate: crate.name)
    for crate in list(chunks(crates, parallel_chunks))[parallel_n]:
        print(
            f"\033[0Ksection_start:{int(time.time())}:"
            f"{crate.name}[collapsed=true]\r\033[0KChecking {crate.name}..."
        )
        sys.stdout.flush()
        test_crate(crate)
        sys.stdout.flush()
        print(f"\033[0Ksection_end:{int(time.time())}:{crate.name}\r\033[0K")


if __name__ == "__main__":
    main()
